# Generated by Django 5.0.3 on 2024-03-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(max_length=255, upload_to='pdfs/'),
        ),
    ]
